### PR TITLE
Read data from folder structure 

### PR DESCRIPTION
**Pull request by talhaanwarch**
Code to test
```
from torcheeg.datasets import FolderDataset
from torcheeg import transforms
import mne


label_map = {'folder1':0,'folder2':1}

def read_file(file_path, chunk_size):
    """
    This function should be provided by user.
    """
    fs = 250
    datax=mne.io.read_raw_edf(file_path,preload=True)
    datax.set_eeg_reference()
    datax.filter(l_freq=1,h_freq=45)
    epochs=mne.make_fixed_length_epochs(datax,duration=chunk_size // fs,overlap=0)
    epochs.drop_bad(reject=None, flat=None)
    return epochs #trials,channel,length


dataset = FolderDataset(io_path=f'raw_output', 
                    root_path='data',
                    num_worker=12, 
                    read_func =   read_file,   
                    online_transform=transforms.Compose([
                      transforms.ToTensor(apply_to_baseline=True),
                      transforms.BaselineRemoval(),
                      transforms.MeanStdNormalize(),
                      transforms.To2d(),
                        ]),
                    label_transform=transforms.Compose([
                      transforms.Select('label'),
                      transforms.Lambda(lambda x: label_map[x] )
                      ])
                      )
```

### CODE REVIEW

**Comment by tczhangzhi** [comment]
Well done! We appreciate your contribution, and agree the overall idea is reasonable.

**Comment by tczhangzhi** [comment]
Hey~ Do you want to continue working on this branch? Or I consider merging it into the `develop` branch and modifying it according to the comments of the review.

**Comment by talhaanwarch** [comment]
Let me create a test case, then i will update it

**Comment by talhaanwarch** [comment]
Hi, @tczhangzhi I made few changes in the test file. Instead of using some existing data, I created a random dataset on the fly and then read back that data.

**Comment by tczhangzhi** [comment]
The logic of the simulated data looks fine. Actually, rather than actually creating folders and files on the file system, I generally prefer to use `unittest.mock` [1].

However, I feel it is acceptable for the current use case as well. I plan to refactor the test cases for other datasets first (they even require the network to download the data or pre-store the data in a designated location). After all, a full CI without internet dependence is a necessity in the PyTorch community.

[1] https://docs.python.org/3/library/unittest.mock-examples.html.

**Comment by tczhangzhi** [comment]
I think this branch is ready to be merged, I will merge this branch, do minor refactoring (according to #30 ), and solve some problems in the review process.

**Pull request merged**
