### PR TITLE
feat: support dynamic shape for plot_feature_topomap

### PR DESCRIPTION
**Pull request by wufei-png**

### CODE REVIEW

**Comment by wufei-png** [comment]
My dataset uses [faced](https://www.synapse.org/#!Synapse:syn50614194/wiki/620378), which has nine classes, which resulted in a drawing that was too long, so I added the adjustable shape feature：
shap

3*3 shape is easier to watch:
shap99


besides, I found this test cannot be passed:
https://github.com/torcheeg/torcheeg/blob/2edf33dc269b89db7ed7951ebbee8a5dac7992ec/test/utils/test_visualize.py#L27
my result shape is **(350, 1550, 4)**:
```
Traceback (most recent call last):
  File "/home/wufei/github.com/wufei-png/torcheeg/test/utils/test_visualize.py", line 17, in test_plot_raw_topomap
    self.assertEqual(img.shape, (347, 1550, 4))
AssertionError: Tuples differ: (350, 1550, 4) != (347, 1550, 4)
```
 same shape mismatches occur with one or two other graphing functions.

My test steps were, first make sure torcheeg is not installed over the network, then `python setup.py -install` then `python test_visualize.py`， I can't see what's wrong.
It's a bit strange, I would suggest you to check if this shape is correct, it's also possible that we have different versions of torcheeg's dependency libraries.
If your test is fine, then see **if my newly added test code matches your results, whichever is yours**

**Comment by wufei-png** [comment]
I have to say that this repository is very useful for us to train the baseline model, thanks, I'm going to add the above mentioned [faced dataset](https://www.synapse.org/#!Synapse:syn50614194/wiki/620378) to torcheeg, when I have some time.

**Comment by tczhangzhi** [comment]
Thank you for your contribution. The code implementation looks very standard. I will directly merge them. This contribution will be noted in the changelog for the next version update.

**Comment by tczhangzhi** [comment]
I will uniformly refactor the test cases for the plotting part.

**Pull request merged**
