### PR TITLE
Add support for MOABB

### PR DESCRIPTION
**Pull request by tczhangzhi**

### CODE REVIEW

**Comment by tczhangzhi** [comment]
It worked well on parts of datasets, so we merged it into the main branch first. Meanwhile, a dataset interface to Braindecode is under development.

I think we need full CI before release, which is the next priority.

```
from moabb.datasets import BNCI2014001
from moabb.paradigms import LeftRightImagery
import torcheeg.datasets.moabb as moabb_dataset
from torcheeg import transforms

if __name__ == '__main__':

    dataset = BNCI2014001()
    dataset.subject_list = [1]
    paradigm = LeftRightImagery()
    dataset = moabb_dataset.MOABBDataset(dataset=dataset,
                           paradigm=paradigm,
                           io_path='./moabb',
                           offline_transform=transforms.Compose(
                               [transforms.BandDifferentialEntropy()]),
                           online_transform=transforms.ToTensor(),
                           label_transform=transforms.Compose([
                               transforms.Select('label')
                           ]),
                           num_worker=2)
    print(dataset[0])
```

**Comment by tczhangzhi** [comment]
An interesting application, I use MoABB's PhysionetMI a lot and it is now accepted by TorchEEG.

```
from torcheeg.datasets.moabb import MOABBDataset
from moabb.datasets import PhysionetMI
from moabb.paradigms import LeftRightImagery
from torcheeg import transforms

import mne


def before_trial(raw: mne.io.Raw) -> mne.io.Raw:
    # raw is an instance of RawEDF
    # # scale to uV
    # raw = raw.apply_function(lambda x: x * 1e6)
    # pick channels
    raw = raw.pick_channels(['FC5', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'FC6', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6',\
                        'CP5', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'CP6', 'Fp1', 'Fpz', 'Fp2', 'AF7', 'AF3', 'AFz',\
                        'AF4', 'AF8', 'F7', 'F5', 'F3', 'F1', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT7', 'FT8', 'T7', 'T8',\
                        'T9', 'T10', 'TP7', 'TP8', 'P7', 'P5', 'P3', 'P1', 'Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3',\
                        'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2', 'Iz'])
    # filter
    raw = raw.filter(4., 38.)
    # common average reference
    raw = raw.set_eeg_reference(ref_channels='average', projection=True)
    # Average reference projection was added, but has not been applied yet. Use the apply_proj method to apply it.
    raw.apply_proj()
    # resample
    raw = raw.resample(128, npad='auto')
    return raw


dataset = PhysionetMI()
paradigm = LeftRightImagery()
dataset = MOABBDataset(dataset=dataset,
                       paradigm=paradigm,
                       chunk_size=128,
                       io_path='../tmp_out/meegmmidb',
                       download_path='../tmp_in/EEGMMIDB',
                       before_trial=before_trial,
                       offline_transform=transforms.Compose(
                           [transforms.MeanStdNormalize(),
                            transforms.To2d()]),
                       online_transform=transforms.ToTensor(),
                       label_transform=transforms.Compose([
                           transforms.Select('label'),
                           transforms.Mapping({
                               'left_hand': 0,
                               'right_hand': 1
                           })
                       ]),
                       num_worker=4)
print(dataset[0])
```

**Comment by bruAristimunha** [comment]
That's great! I must say, the structure is truly impressive. I find it fascinating that you provide users with control over this type of transformation.

Allow me to offer a suggestion: you can incorporate part of this process using moabb. By default, moabb already includes some transformations across all datasets. This aligns with the philosophy of moabb, where we systematically apply a consistent set of transformations to all datasets. For instance, we apply filters at the same frequency to establish a fair comparative space and create a benchmark environment that is fair for all datasets. It might be beneficial to enhance the flexibility of this structure within moabb, enabling the application of additional processes such as re-scaling and re-referencing of channels.

Here's the corresponding code snippet:

```python
from torcheeg.datasets.moabb import MOABBDataset
from moabb.datasets import PhysionetMI
from moabb.paradigms import LeftRightImagery
from torcheeg import transforms

import mne


def before_trial(raw: mne.io.Raw) -> mne.io.Raw:
    # raw is an instance of RawEDF   
    # common average reference
    raw = raw.set_eeg_reference(ref_channels='average', projection=True)
    # Average reference projection was added, but has not been applied yet. Use the apply_proj method to apply it.
    raw.apply_proj()
    #  scale to uV
    raw = raw.apply_function(lambda x: x * 1e6)
    return raw


dataset = PhysionetMI()
paradigm = LeftRightImagery(fmin=4, fmax=8, channels=['FC5', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'FC6', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6',  'CP5', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'CP6', 'Fp1', 'Fpz', 'Fp2', 'AF7', 'AF3', 'AFz',\
                        'AF4', 'AF8', 'F7', 'F5', 'F3', 'F1', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT7', 'FT8', 'T7', 'T8',\
                        'T9', 'T10', 'TP7', 'TP8', 'P7', 'P5', 'P3', 'P1', 'Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3',\
                        'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2', 'Iz']), resample = 128, ... )



dataset = MOABBDataset(dataset=dataset,
                       paradigm=paradigm,
                       chunk_size=128,
                       io_path='../tmp_out/meegmmidb',
                       download_path='../tmp_in/EEGMMIDB',
                       before_trial=before_trial,
                       offline_transform=transforms.Compose(
                           [transforms.MeanStdNormalize(),
                            transforms.To2d()]),
                       online_transform=transforms.ToTensor(),
                       label_transform=transforms.Compose([
                           transforms.Select('label'),
                           transforms.Mapping({
                               'left_hand': 0,
                               'right_hand': 1
                           })
                       ]),
                       num_worker=4)
print(dataset[0])
```

Furthermore, the paradigms [p300/ERP](http://moabb.neurotechx.com/docs/generated/moabb.paradigms.SinglePass.html#moabb.paradigms.SinglePass), [MotorImagery](http://moabb.neurotechx.com/docs/generated/moabb.paradigms.MotorImagery.html#moabb.paradigms.MotorImagery) (with LeftRightImagery as a subclass), and [SSVEP](http://moabb.neurotechx.com/docs/generated/moabb.paradigms.SSVEP.html#moabb.paradigms.SSVEP) contain values that aim to emphasize specific brain bands associated with each paradigm.

I'll finish testing moabb dataset with this wonderful new dataloader from TorchEEG =)

cc. @sylvchev

**Comment by tczhangzhi** [comment]
I think the suggested snippet makes a lot of sense! Thank you for your support and contributions ＼(＠＾０＾＠)/

**Pull request merged**
